server:
  port: 8081

spring:
  application:
    name: interviewer-service
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/interviewer_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
 
eureka:
  instance:
    hostname: localhost
 