
server:
  port: 8082

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/InterviewFeedback_db
  application:
    name: feedback-service

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka